# Generated by Django 3.2.16 on 2023-04-01 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_alter_post_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="following",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow",
                to="auth.user",
            ),
            preserve_default=False,
        ),
    ]
